### ISSUE TITLE
Developer documentation seems to be missing

### ISSUE THREAD

**Issue by pjljvandelaar** [AdaCore/spark2014#17]
Dear AdaCore,

I would like to experiment with the spark2014 code, however I can't nowhere find any documentation for developers. Is this not available?

The developer documentation should answer general questions like
* What is the architecture of Spark2014?
* What are the mayor components and their interfaces?
* Is their a docker environment to experiment with Spark2014?
* Does gnatprove use the libadalang as library to represent ada code?
* What is the expected development platform? I assume it isn't windows, since I am getting a lot of style errors: `gnatprove.adb:1:79: (style) incorrect line terminator`

and specific questions like:

* Why does gnatprove.gpr specify `Sources := (".", "src/gnatprove", "src/common");`, while in the git archive has more subdirectories in the directory `src`.
* Why is "src/common" added twice to Sources in gnatrpove.gpr? i.e. lines 16-18:
  ```
   Sources := (".", "src/gnatprove", "src/common");

   Sources := Sources & ("src/common/" & Target);
  ```
* How does gnatprove proof the flow of programs, without having access to the sources in `src/flow`?

**Comment by yannickmoy** [comment]
Dear @pjljvandelaar 

The developer doc is in docs/develguide, you can build the HTML version with "make html". It should answer most of your high-level questions. In particular, "gnatprove" is the driver for verifiation, it calls "gnat2why" for every unit it analyzes, which takes care of applying flow analysis and proof.

Regarding more specific questions:
- we don't provide a docker env, for using GNATprove you can download it for your host at https://www.adacore.com/download
- GNATprove is based on the GNAT compiler frontend, not on Libadalang, for its frontend (as presented in the paper "Hi-Lite: the convergence of compiler technology and program verification" at http://www.open-do.org/wp-content/uploads/2012/11/HILT_2012.pdf)
- you can develop GNATprove on any host, but indeed we consistently use Linux end-of-line terminators
- Target is appended to src/common with the syntax "a & b" borrowed from Ada in the syntax of GPR files, so src/common is not added twice

Hope you find it useful!

**Comment by pjljvandelaar** [comment]
@yannickmoy Thanks for your promptly answer!
I am however not able to correctly build the developer guide:
I get
```
PS C:\AdaCore\spark2014\docs\develguide> make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v2.0.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: [] 0 added, 3 changed, 0 removed
reading sources... [100%] manual_proof
C:\AdaCore\spark2014\docs\develguide\counterexamples.rst:656: WARNING: Error in "code-block" directive:
maximum 1 argument(s) allowed, 5 supplied.

.. code-block:: whyml
   val spark__branch "model_trace:0000": bool__ref
C:\AdaCore\spark2014\docs\develguide\counterexamples.rst:521: WARNING: download file not readable: C:\AdaCore\spark2014\gnat2why\why\gnat2why-util.ads
C:\AdaCore\spark2014\docs\develguide\counterexamples.rst:543: WARNING: download file not readable: C:\AdaCore\spark2014\common\vc_kinds.ads
C:\AdaCore\spark2014\docs\develguide\counterexamples.rst:585: WARNING: download file not readable: C:\AdaCore\spark2014\gnat2why\why\gnat2why-counter_examples.ads
C:\AdaCore\spark2014\docs\develguide\counterexamples.rst:592: WARNING: download file not readable: C:\AdaCore\spark2014\gnat2why\why\gnat2why-counter_examples.adb
C:\AdaCore\spark2014\docs\develguide\counterexamples.rst:659: WARNING: download file not readable: C:\AdaCore\spark2014\gnat2why\why\why-gen-expr.adb
C:\AdaCore\spark2014\docs\develguide\counterexamples.rst:679: WARNING: download file not readable: C:\AdaCore\spark2014\gnat2why\why\gnat2why-expr.adb
C:\AdaCore\spark2014\docs\develguide\counterexamples.rst:690: WARNING: download file not readable: C:\AdaCore\spark2014\gnat2why\why\gnat2why-counter_examples.adb
C:\AdaCore\spark2014\docs\develguide\counterexamples.rst:705: WARNING: download file not readable: C:\AdaCore\spark2014\gnat2why\why\ce_interval_sets.ads
C:\AdaCore\spark2014\docs\develguide\gnatwhy3.rst:216: WARNING: Bullet list ends without a blank line; unexpected unindent.
C:\AdaCore\spark2014\docs\develguide\gnatwhy3.rst:218: WARNING: Unexpected indentation.
C:\AdaCore\spark2014\docs\develguide\gnatwhy3.rst:512: WARNING: download file not readable: C:\AdaCore\spark2014\why3\theories\int.why
looking for now-outdated files... none found
pickling environment... done
checking consistency... C:\AdaCore\spark2014\docs\develguide\libraries.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] manual_proof
generating indices... genindex
writing additional pages... search
copying downloadable files... [100%] ../why3/src/session/itp_server.mli        d.mlwexmp.ml
copying static files... WARNING: html_static_path entry 'C:\\AdaCore\\spark2014\\docs\\develguide\\_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 14 warnings.

The HTML pages are in _build\html.
ECHO is off.
"Build finished. The HTML pages are in _build/html."
```
The paths `C:\AdaCore\spark2014\common\` and `C:\AdaCore\spark2014\gnat2why\why\` do not exist in the spark2014 archive.
Do I have to build components, before I can build its documentation?

**Comment by yannickmoy** [comment]
Thanks for reporting it, we've moved some subdirectories recently, and the dev guide has not been updated here. We'll fix it. In the meantime, that only breaks some links to the code from the doc, which you can read at _build/html/index.html

**Comment by kanigsson** [comment]
Hi, some more details for your questions:

- You can build SPARK on windows, and git can convert line endings automatically for you, see e.g. this https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings
- `gnatprove.gpr` does *not* add `src/common` twice to the list, the `&` operator is the concatenation for strings, not the concatenation for the path list.
- `gnatprove.gpr` is the project file just for the `gnatprove` (and other) executable, but SPARK contains other executables, in particular `gnat2why` which is built via `gnat2why/gnatwhy.gpr`. The location of this project file is strange for historic reasons, and we will probably improve that soon.
- `src/flow` is part of the `gnat2why` executable.
