### ISSUE TITLE
typos and wrong sentences

### ISSUE THREAD

**Issue by pjljvandelaar** [AdaCore/spark2014#18]
Since legal is looking into your contribution license, I can't deliver a patch yet.

Yet, typos and wrong sentences can be corrected by AdaCore without any license issue:
So here is my current list of observations:
* https://github.com/AdaCore/spark2014/blob/7c6d16b434697d45b09b2e7527190582efd8b66c/src/flow/flow-analysis.ads#L102 hideen -> hidden
* https://github.com/AdaCore/spark2014/blob/7c6d16b434697d45b09b2e7527190582efd8b66c/src/flow/flow-analysis.ads#L115 immidiately -> immediately
* https://github.com/AdaCore/spark2014/blob/7c6d16b434697d45b09b2e7527190582efd8b66c/src/flow/flow-analysis.ads#L157-L158 twice `this is enough`

**Comment by yannickmoy** [comment]
thanks, fix is on review. for similar fixes in the future, let's wait for the approval of your legal team, so that you can directly propose a patch.
