### ISSUE TITLE
developer guide: issues

### ISSUE THREAD

**Issue by pjljvandelaar** [AdaCore/spark2014#19]
In file:///C:/AdaCore/spark2014/docs/develguide/_build/html/tool_structure.html, in section `Using gprbuild` is written
```
At the minimum the Driver attribute must be set to gnatw2hy.
gnatwhy produces compiler-like output. But note that gprbuild holds back the output of gnat2why until the tool has finished completely. This can create some confusion in a debugging context.
```
Am I right in assuming `gnatw2hy` is a typo of `gnat2why`.
Is `gnatwhy` also a typo or is it another tool like `gnat2why` and `gnatwhy3`?

**Comment by yannickmoy** [comment]
I fixed the typo, thanks, we have enough with gnat2why and gnatwhy3 :-)
