### ISSUE TITLE
gnat2why FSF build fails - "Ada_Text_IO_Child" is undefined

### ISSUE THREAD

**Issue by steve-cs** [AdaCore/spark2014#21]
Within the last few days updates to GCC/master appear to have broken the FSF build of SPARK2014.  I believe the only change to my nightly build at that time was updated ```./gnat2why/gnat_src```.  Should the spark2014/fsf branch be following gcc/master or gcc/releases/gcc-10 at the present time?

Summary:
```
gprbuild  -Pgnat2why -j0 -cargs  -largs 
Compile
[...]
   [Ada]          flow_visibility.adb
flow_visibility.adb:510:19: "Ada_Text_IO_Child" is undefined
flow_visibility.adb:516:19: "Ada_Wide_Text_IO_Child" is undefined
flow_visibility.adb:522:19: "Ada_Wide_Wide_Text_IO_Child" is undefined
   compilation of flow_visibility.adb failed
gprbuild: *** compilation phase failed
```

Full log: https://travis-ci.org/github/steve-cs/travis-test/builds/695047686

**Comment by pmderodat** [comment]
Hello,

Thank you for reporting this issue. We just synchronized the `fsf` branch to the GCC sources at the FSF. Please let us know if you still have build issues.

**Comment by steve-cs** [comment]
@pmderodat Broken in a different place.

```
gprbuild  -Pgnat2why -j0 -cargs  -largs 
Compile
[...]
   [Ada]          flow_utility.adb
flow_utility.adb:2747:48: "Get_Index_Subtype" is undefined (more references follow)

   compilation of flow_utility.adb failed

gprbuild: *** compilation phase failed
```

**Comment by pmderodat** [comment]
Hello again @steve-cs,

My mistake: in order to synchronize the `fsf` branch and the GCC sources, I used git commit date, whereas I should have used the merge date instead. This should now be fixed, sorry for the inconvenience!

**Comment by steve-cs** [comment]
gnat2why, gnatprove now build.  So that looks to be the end of gcc version problems.  But I run into a different problem towards the end of building why3 that I haven't seen before.

FYI.
```
make[2]: Leaving directory '/home/steve/gnat-builder/spark2014-build/why3'
mv ./why3/bin/why3.opt ./install/libexec/spark/bin/why3.opt
mv: cannot move './why3/bin/why3.opt' to './install/libexec/spark/bin/why3.opt': No such file or directory
Makefile:84: recipe for target 'why3' failed
make[1]: *** [why3] Error 1
make[1]: Leaving directory '/home/steve/gnat-builder/spark2014-build'
Makefile:708: recipe for target 'spark2014' failed
```
I don't think this is my problem, but I'm not sure.  I'll track this down later and open a different issue unless you want to look at it first.  No hurry.

Thanks!

**Comment by kanigsson** [comment]
Yes please open a new issue if your problem persists.
