### ISSUE TITLE
fsf branch why3 build missing './install/libexec/spark/bin/' path

### ISSUE THREAD

**Issue by steve-cs** [AdaCore/spark2014#22]
fsf branch appears to still be missing some commits in the recent sync.  Build now fails with:

```
mv ./why3/bin/why3.opt ./install/libexec/spark/bin/why3.opt
mv: cannot move './why3/bin/why3.opt' to './install/libexec/spark/bin/why3.opt': No such file or directory
Makefile:84: recipe for target 'why3' failed
make[1]: *** [why3] Error 1
make[1]: Leaving directory '/home/steve/gnat-builder/spark2014-build'
make: *** [spark2014] Error 2
```
Full log: https://travis-ci.org/github/steve-cs/travis-test/builds/696040338

This appears to be the same issue as "T211-001 fix generation of JSON file for menus" which was resolved with master branch commit https://github.com/AdaCore/spark2014/commit/1a76ce2632c7bfc4961e4bbd1b633c63b6eb2fee

However that fix doesn't work in fsf branch as gnatwhy3.opt doesn't understand '--list-transforms' yet and the why3 build then fails with:

```
make[2]: Leaving directory '/home/steve/gnat-builder/spark2014-build/why3'
why3/bin/gnatwhy3.opt --list-transforms | python scripts/why3menus.py share/spark/config/generated_menus.json
why3/bin/gnatwhy3.opt: unknown option '--list-transforms'.
Usage: gnatwhy3 [options] file
  --version            Print version information and exit
  --show-config        Print configuration information and exit
[...]
Makefile:84: recipe for target 'why3' failed
make[1]: *** [why3] Error 1
make[1]: Leaving directory '/home/steve/gnat-builder/spark2014-build'
Makefile:708: recipe for target 'spark2014' failed
make: *** [spark2014] Error 2
```
(Edit - added full log from Travis CI)

**Comment by pmderodat** [comment]
Hello,

I’m currently in the process of pushing all our internal GNAT patches to the FSF (several hundreds commits): this happens every year, because of all the commits we do on GNAT while the development branch is frozen at the FSF, and I’m updating spark2014’s `fsf` branch in sync. Given that I’m pushing 30 commits per day at the FSF and that the commit you mention has been merged in spark2014 in March, 31st, so at the current pace, it should land in the `fsf` branch in several days.

**Comment by kanigsson** [comment]
Hello Steve, 

If you can't wait, you can just remove the two lines after `make -C why3` in the failing Makefile target. These lines are just generating a file that is already checked in with the correct contents.

**Comment by steve-cs** [comment]
FYI.  With that patch spark2014/fsf now builds for me.  I didn't imagine it would be that simple.  Thanks.

No inconvenience at all waiting for things to settle.

**Comment by kanigsson** [comment]
Thanks for your feedback.
