### ISSUE TITLE
fsf branch out of sync with FSF GCC ?

### ISSUE THREAD

**Issue by steve-cs** [AdaCore/spark2014#24]
fsf branch failing to build for the past two weeks with:

```
spark_definition.adb:1231:07: missing case value: "N_Iterated_Element_Association"
spark_definition.adb:6168:15: "E_Protected_Object" is undefined

```
Also an "E_Protected_Object" is undefined complaint will occur while compiling flow_utility.adb

The following patch is what I'm currently using to enable a successful build.  While removing the references to E_Protected_Object might be a reasonable solution, the added N_Iterated_Element_Association I made is almost certainly wrong or in the wrong place.

https://github.com/steve-cs/gnat-builder/blob/master/spark2014-patch.diff

**Comment by kanigsson** [comment]
Hello Steve,

The engineer keeping up to date the fsf branch is on vacation, I'm sure he will figure it out when he's back. In the meantime, you can look at these commits and do something similar:

3a9066c1f96e2b2bb055141807d2ac248e84a503
2a942a171bb77f36acb868b24be1955816eac53f

**Comment by steve-cs** [comment]
That does/confirms it.  Thanks.

**Comment by pmderodat** [comment]
Hello @steve-cs,

I indeed forgot to do the `fsf` branch sync immediately after porting the last series of GNAT patches, then a personal emergency took me away from keyboard a full week: sorry again for the inconvenience! This should now be fixed, please let us know if not. Thanks,

**Comment by steve-cs** [comment]
Hello @pmderodat,

FYI.  spark2014/fsf build broke 7 days ago related to Long_Long_Long_Integer standard type in gcc/master.  Fixed with commit https://github.com/AdaCore/spark2014/commit/9bb9497608bb69d1fb0768f2edfb998543a55182.

**Comment by ArnaudCharlet** [comment]
Indeed, sorry for the inconvenience. Glad you found workaround already. Another workaround is to use commit eb6ea9e54f1f2 from gcc/master.

**Comment by steve-cs** [comment]
@ArnaudCharlet, unable to confirm your alternative workaround with most recent gcc version 11.0.0 20200910 (experimental)  that should contain eb6ea9e54f1f2 commit.

```
spark_definition.adb:7323:10: missing index value in array aggregate
spark_definition.adb:7323:10:   "S_Long_Long_Long_Integer"

   compilation of spark_definition.adb failed
```
```
steve@ubuntu:~/gnat-builder$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-linux-gnu/11.0.0/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../gcc-src/configure --prefix=/usr/local --host=x86_64-linux-gnu --build=x86_64-linux-gnu --target=x86_64-linux-gnu --enable-languages=c,c++,ada --disable-bootstrap
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.0.0 20200910 (experimental) (GCC) 
steve@ubuntu:~/gnat-builder$ 
```

**Comment by ArnaudCharlet** [comment]
Sorry if I wasn't clear: you must use exactly commit eb6ea9e54f1f2 and not a more recent one which introduce the problematic change.

**Comment by steve-cs** [comment]
That makes much perfect sense now.  I'm going to stick with patching spark2014/fsf branch unless it falls too far behind  FSF GCC/master for nightly development builds. Thanks again.

**Comment by ArnaudCharlet** [comment]
Sounds good!

**Comment by steve-cs** [comment]
FYI.  Just a status update.  A different issue with respect to Is_Effectively_Volatile_For_Reading and Is_Effectively_Volatile_Object_For_Reading not being defined currently breaks the build of spark_definition.adb and flow-analysis.adb.  I have updated my local patch to effectively revert commit https://github.com/AdaCore/spark2014/commit/7e582c126b7d04817cd748128a990a52dd5f570d (not including tests).  That seems to fix things (at least the build) for me.

**Comment by pmderodat** [comment]
Hello @steve-cs,

Things should be back in order, now: builds using the current GCC `master` branch at the FSF and this repos’ `fsf` branch should be fine. Could you confirm? Thank you in advance!

**Comment by steve-cs** [comment]
Hello @pmderodat,

Confirming, builds fine without patches here too.

**Comment by pmderodat** [comment]
Great, thank you for the confirmation!
