### ISSUE TITLE
Linking error of gnatvsn.o when building from source (FSF)

### ISSUE THREAD

**Issue by 1ma** [AdaCore/spark2014#30]
```
    ...
    [Ada]          gnat2why-ce_utils.adb
    [Ada]          name_ordered_entities.adb
    [Ada]          flow_generated_globals-phase_1-write.adb
 Bind
    [gprbind]      gnat1drv.bexch
    [Ada]          gnat1drv.ali
 Link
    [archive]      libgnat2why.a
    [index]        libgnat2why.a
    [link]         gnat1drv.adb
/usr/bin/ld: /tmp/Spark2014/gnat2why/obj/gnatvsn.o: in function `gnatvsn__gnat_version_string':
/tmp/Spark2014/gnat2why/gnat_src/gnatvsn.adb:66: undefined reference to `gnat_version_string'
/usr/bin/ld: /tmp/Spark2014/gnat2why/gnat_src/gnatvsn.adb:68: undefined reference to `gnat_version_string'
collect2: error: ld returned 1 exit status
gprbuild: link of gnat1drv.adb failed
gprbuild: failed command was: /usr/local/gcc/bin/gnatgcc gnat1drv.o @/tmp/GNAT-TEMP-000026.TMP
make[1]: Leaving directory '/tmp/Spark2014/gnat2why'
make[1]: *** [Makefile:76: build] Error 4
make: *** [Makefile:133: gnat2why] Error 2
```

The build environment is the same described in #29, copied here verbatim from the other issue:

Platform: Ubuntu 20.04
Spark2014 commit: 5da8c83 (tip of fsf branch)
GCC commit: gcc-mirror/gcc@6bebd55 (the last of a batch of Ada-related commits merged a minute earlier than 5da8c83)
xmlada commit: AdaCore/xmlada@337bce3 (tip of master)
libgpr commit: AdaCore/gprbuild@dcc8dba (tip of master)
gnatcoll commit: AdaCore/gnatcoll-core@5b8e83e (tip of master)
Ocaml: 4.07.1

For now, in order to complete the compilation I had to [write my own dummy implementation](https://github.com/1ma/dockertronics/blob/68f88403ea9142d8e969bf676ccc2a3590766a35/gnat/spark/gnatvsn.adb#L56)  of `Gnatvsn.Gnat_Version_String` and [overwrite gnatvsn.adb](https://github.com/1ma/dockertronics/blob/68f88403ea9142d8e969bf676ccc2a3590766a35/gnat/spark/Dockerfile#L39) in the gcc source. The original file is [this one](https://github.com/gcc-mirror/gcc/blob/6bebd55e12375b397ed187630bb57d58611dfc5f/gcc/ada/gnatvsn.adb#L61).

**Comment by pmderodat** [comment]
Hello @1ma ,

The `fsf` branch should now be fixed, so you should be able to build without your workaround. Sorry for the delay, and thanks again for reporting!
