### ISSUE TITLE
Colibri prover?

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/spark2014#36]
I’ve built branch fsf against GCC 12.0.1 of 20220204 ([discussion](https://forward-in-code.blogspot.com/2022/02/spark2014-and-fsf-gcc.html), [compiler](https://github.com/simonjwright/distributing-gcc/releases/tag/gcc-12.0.1), [spark2014](https://github.com/simonjwright/spark2014/releases/tag/macos-0.1)).

Running SPARKNaCl fca8934 of 16 December (latest) against this, I get 6 unproved checks.

Running the testsuite, I get a massive number of fails. I checked 5 failing tests at random, they failed because colibri wasn’t installed. Out of 1500 tests run as I write, none of the ug tests have failed, and overall 500 tests have passed.

Is colibri available? A web search failed to find it.

**Comment by yannickmoy** [comment]
Hi @simonjwright, 

Congrats on completing the build of GNAT and SPARK for Mac! and many thanks for making the builds available to all.

Building COLIBRI is yet another level of complexity, as it requires using ECLiPSe Prolog. I'll let @kanigsson comment on the feasibility of doing that on Mac. You can get the sources from GNAT Community 2021 at https://www.adacore.com/download/more. The source package is called `colibri-2021-20210518-19CDE-src.tar.gz`. 

Note that the team developing COLIBRI has started a reboot called COLIBRI2, which is in OCaml and [available through opam](https://colibri.frama-c.com/html/get-frama-c.html), but it's not ready to replace COLIBRI. 

Until then, it may be easier to just ignore tests that require COLIBRI.

**Comment by simonjwright** [comment]
@yannickmoy, thanks for that! but I think I’ll skip building COLIBRI if that’s what it takes!

Is running just the ug* tests useful for me? so far only `ug__simple_loops_cdp` fails (needs CodePeer).

Would a report of the SPARKNaCl failures be helpful to you? In a separate issue, maybe?

**Comment by yannickmoy** [comment]
Looks like a sane decision! :-)

The ug* tests are those that correspond to code snippets and results that we display as part of the SPARK User's Guide, so indeed it's a good sanity check that the build is ok.

For SPARKNaCl, I assume you're referring to checks that don't get proved with the current version? You could report them to Rod under the `sparknacl` GitHub project, as a heads-up for the next time he updates his version of SPARK. It's expected that, when you change the version of provers, you may have to rework ghost code that drives them.

**Comment by simonjwright** [comment]
ug*: aside from the CodePeer failure, there’s one more:
```
INFO     FAIL            ug__invariants: unexpected output
Diff failure: unexpected output
--- expected
+++ output
@@ -1 +1,2 @@
+
 
@@ -6,3 +7,5 @@
       |             ^~~~
+      |             ^~~~
       |             ^~~~~~~~~~~~~
+   13 |   procedure Push (S : in out Stack; E : Element) with
    21 |   procedure Push (E : Element) with
@@ -30,3 +33,3 @@
 invariants.adb:6:41: info: range check proved
-invariants.ads:13:14: info: invariant check proved
+invariants.ads:13:14: medium: invariant check might fail
 invariants.ads:14:13: info: invariant check proved
```

**Comment by kanigsson** [comment]
Hello Simon,

I don't know about Mac, but for Linux compilation of COLIBRI is not more complicated than what you have already done. You need to compile eclipse prolog, then compile COLIBRI from the source package that Yannick indicated. It's just `make` and `make install`, but the Makefile requires some settings. You need to set `DLLSUFFIX` to `so`, `ECLIPSEARCH` to `x86_64_linux` (note the double underscore) and ECLIPSEBIN to the install dir of eclipse prolog (all values for Linux). The build requires an ocaml setup + GNAT compiler for a small Ada program.

**Comment by kanigsson** [comment]
Simon,

I checked your blog post, nice write-up! Some comments:
- similar to how you did for alt-ergo, you could just grab binaries for cvc4 and z3 from their release download pages. For cvc4 this is based on homebrew I believe.
- For alt-ergo build, if you want to compile it yourself, after the `make install-lib` step, you need to set the OCAMLPATH to contain the path where you installed library. In your case this would be `<prefix>/lib`, I believe.

**Comment by simonjwright** [comment]
Johannes,

Thanks for the comments!

>I don't know about Mac, but for Linux compilation of COLIBRI is not more complicated than what you have already done. You need to compile eclipse prolog, then compile COLIBRI from the source package that Yannick indicated.

I tried building Eclipse-Prolog, much trouble. There is a Mac binary of Eclipse Prolog, from 2013 (probably the last time that team used a Mac), which at least appeared to work.

COLIBRI also had trouble. dune only knows how to build a `.dylib` if you call it `.so` instead. There’s confusion about the architecture (looking for an `include/x86_64_linux/eclipse.h`.) On darwin you need to `#include <machine/endian.h>`. `eclipse.exe` can find its dylibs when called from the command line, but not if it’s called from the Makefile - This Is Puzzling. Then, ... well, you get the picture.

>similar to how you did for alt-ergo, you could just grab binaries for cvc4 and z3 from their release download pages. For cvc4 this is based on homebrew I believe.

z3 looks good - 4.8.12 is there, latest 4.8.14.

Religious objection to homebrew!

Will try the OCAMLPATH tip, thanks.

>If you have trouble with proving via alt-ergo, it is possible that some command line parameters changed between the version we expect in SPARK and the version you compiled via opam.

I have alt-ergo 2.4.1

**Comment by kanigsson** [comment]
Sad to hear that colibri is difficult to compile on Mac. I don't think colibri is essential to your Mac build. I'm closing this ticket as there isn't really anything we can do.

For your alt-ergo issue, we can possibly discuss on a new ticket?

P.S.: You can set the version of SPARK in the file "spark2014vsn.ads".

**Comment by simonjwright** [comment]
> ug*: aside from the CodePeer failure, there’s one more:
> 
> ```
> INFO     FAIL            ug__invariants: unexpected output
> Diff failure: unexpected output
> --- expected
> +++ output
> @@ -1 +1,2 @@
> +
>  
> @@ -6,3 +7,5 @@
>        |             ^~~~
> +      |             ^~~~
>        |             ^~~~~~~~~~~~~
> +   13 |   procedure Push (S : in out Stack; E : Element) with
>     21 |   procedure Push (E : Element) with
> @@ -30,3 +33,3 @@
>  invariants.adb:6:41: info: range check proved
> -invariants.ads:13:14: info: invariant check proved
> +invariants.ads:13:14: medium: invariant check might fail
>  invariants.ads:14:13: info: invariant check proved
> ```

I ran this again, on its own:
```
$ ./run-tests tests/ug__invariants
INFO     Found 1 tests
INFO     PASS            ug__invariants
INFO     Summary:
_  PASS         1
```

**Comment by yannickmoy** [comment]
@simonjwright That's odd indeed. Usually, such cases are due to timeouts, but here the timeout is fixed at 60 seconds (in `run_tests` script, on line 316, for the driver of UG tests), and this test is proved in a few seconds. What value are you passing for `-j` switch when running `run_tests` on all UG tests?

**Comment by simonjwright** [comment]
@yannickmoy I hadn’t specified `-j` at all. With `-j2`, `ug__invariants` passes!

**Comment by yannickmoy** [comment]
@simonjwright I was more worried of a too large value for `-j` that would force processes to swap instead of doing their job. I see no reason why `-j1` would lead to a timeout, so I'm puzzled. But good that you found a setting that works!

**Comment by simonjwright** [comment]
@yannickmoy On the fsf branch, it appears that omitting `-jn` has the same effect as `-j0` - this machine has 4 cores, and without `-jn` I see this in the log file
```
2022-02-24 12:07:04,732: e3.job.scheduler        : DEBUG    non-ready?: False, in queue: 15, running: 4
```
but with `-j2`
```
2022-02-23 11:40:20,226: e3.job.scheduler        : DEBUG    non-ready?: False, in queue: 84, running: 2
```

**Comment by pmderodat** [comment]
Hello! The omission of `-jn` is expected to run one job per available processor: nothing surprising that you have `-j4` by default here. This is a behavior that is common to all our testsuites, usually very developer friendly.

Now, it is perfectly possible to make the SPARK testsuite use `-j1` by default, however @yannickmoy I see that we usually run the SPARK testsuite with `-j8`, `-j16` on our build machine, with even `-j256` on our biggest machine, so I suppose @simonjwright’s OSX machine should have no trouble running it with `-j4`… What do you think?

**Comment by yannickmoy** [comment]
yes, `-j` should not have any adverse effect here, I don't know why @simonjwright got different results on this specific test.
