### ISSUE TITLE
Unsound handling of mod 16 bitwise negation

### ISSUE THREAD

**Issue by ALPHA-60** [AdaCore/spark2014#39]
Gnatprove from Alire "proves" a false postcondition:

Package:

```ada
package Test 
  with Spark_Mode => On
is
   type Nibble is mod 2**4;
   
   procedure Wrong 
     with
       Post => False;
end Test;
```

Body:

```ada
package body Test
with Spark_Mode => On
is
   
   procedure Wrong is
      function Get return Nibble is (1);
      Dummy : constant Nibble := not Get;
   begin
      null;
   end Wrong;
end Test;
```

If any of the following changes is made, the false postcondition is correctly detected:

Function call is replaced by constant:

```patch
-      Dummy : constant Nibble := not Get;
+      Dummy : constant Nibble := not 1;
```

Bitwise negation is replaced by subtraction:

```patch
-      Dummy : constant Nibble := not Get;
+      Dummy : constant Nibble := 15 - Get;
```

Type is extended to mod 256:

```patch
-   type Nibble is mod 2**4;
+   type Nibble is mod 2**8;

```

**Comment by kanigsson** [comment]
The reason for the unsoundness is that we forget to apply a modulus to the result of the negation.
In SPARK, we represent modular types via bitvectors whose size roughly correspond to the Object_Size that is used in Ada. In your case, we use a bitvector of size 8. We then use the negation operation on the bitvector to represent the negation operation in Ada. However, that operation returns 254 (for your example value of 1). But we assume that this value is in the `Nibble` type which only correct if another modulus is applied (which is what happens in Ada).
We are currently validating a fix, which consists in adding the modulus operation. We will also check if it isn't missing in other cases.

**Comment by kanigsson** [comment]
This has been fixed in the development version of gnatprove. Thanks again for your report.

**Comment by ALPHA-60** [comment]
Thanks for fixing this!
