### ISSUE TITLE
gnatprove ignores -aP option

### ISSUE THREAD

**Issue by atupone** [AdaCore/spark2014#4]
I had a Bug issued related to this.

https://bugs.gentoo.org/659724

Small reproducer:

‰ cat repro.sh 
#!/bin/sh
mkdir dir1 dir2
cat > dir1/gfxinit.gpr << EOF
with "libhw";
library project gfxinit is
   for Library_Name use "gfxinit";
end gfxinit;
EOF
cat > dir2/libhw.gpr << EOF
library project libhw is
   for Library_Name use "hw";
end libhw;
EOF
cd dir1
gnatprove -Pgfxinit.gpr -aP=../dir2

‰ ./repro.sh 
gnatprove: gfxinit.gpr:1:06: unknown project file: "libhw"

Error while loading project file: gfxinit.gpr

**Comment by kanigsson** [comment]
Strange ... I was able to  reproduce briefly, but now I can't reproduce anymore, with any version of gnatprove, including SPARK Discovery GPL 2017, SPARK Community 2018, and SPARK Pro 18.
Note that gnatprove is designed to behave like gprbuild - when I was briefly able to reproduce, gprbuild had the same behavior.
As a workaround, you can use GPR_PROJECT_PATH (as discussed on that gentoo ticket).

**Comment by l29ah** [comment]
Maybe you've exported GPR_PROJECT_PATH in your shell?

**Comment by kanigsson** [comment]
No I haven't.

I tried some more - I'm still unable to reproduce using gnatprove, but now I can reliably reproduce using gprbuild.

Can you try to replace `-aP=../dir2` by `-aP dir2`? In other words, replace the  equal sign by a space. Does this work?

Also, what happens on your machine if you replace gnatprove by gprbuild? Do you see the same behavior as gnatprove or a different behavior? Both for passing the argument with an equal sign or with a space.
