### ISSUE TITLE
Simple Sieve of Eratosthenes program triggers "(spark) GCC error: Error while reading SMT model ..."

### ISSUE THREAD

**Issue by dev-muppet** [AdaCore/spark2014#41]
A 40 line Sieve of Eratosthenes program triggers this error:

```
gnatprove -PC:\spark\sieve\sieve.gpr -XADAFLAGS= --output=oneline --ide-progress-bar -u sieve.adb --counterexamples=on --proof-warnings --level=1 -j0
Phase 1 of 2: generation of Global contracts ...
Phase 2 of 2: flow analysis and proof ...
+===========================GNAT BUG DETECTED==============================+
| 1.0 (spark) GCC error:                                                   |
| Error while reading SMT model:
Cannot parse as S-expression at                                            |
|     character 17741.
[...]
```

This is the sieve.adb file that triggers the error:

```
with Text_IO;                           use Text_IO;
with Ada.Numerics.Elementary_Functions; use Ada.Numerics.Elementary_Functions;

procedure Sieve with
   SPARK_Mode
is

   type Boolean_Array is array (Positive range <>) of Boolean;

   procedure Sieve (N : Positive) is
      B                 : Boolean_Array (2 .. N) := (others => True);
      Sqrt_N_Rounded_Up : constant Positive      :=
        Positive (Float'Ceiling (Sqrt (Float (N))));
      Num_Primes : Natural := 0;
   begin
      for I in 2 .. Sqrt_N_Rounded_Up loop
         declare
            J : Positive := I + I;
         begin
            while J <= N loop
               B (J) := False;
               J     := J + I;
            end loop;
         end;
      end loop;
      Put ("Primes: ");
      for I in 2 .. N loop
         if B (I) then
            Num_Primes := Num_Primes + 1;
            Put (I'Image);
         end if;
      end loop;
      New_Line;
      Put_Line ("Num Primes: " & Num_Primes'Image);
   end Sieve;

   N : constant Positive := 100;
begin
   Sieve (N);
end Sieve;
```

I'm using the newest gnatprove packaged with alire, version 12.1.1.

Note: I only see this "Error while reading SMT model" bug when using the GNAT Studio "Prove File" option (Ctrl+Alt+F). For example, if I do "Prove Subprogram" (Ctrl+Alt+S), this bug doesn't happen, and I get the usual messages about overflow checks that might fail, etc.

**Comment by kanigsson** [comment]
Thanks for your report. This issue is already fixed in the development version of SPARK. You can avoid it by disabling counterexamples (switch `--counterexamples=off`).

**Comment by dev-muppet** [comment]
Thanks Johannes. As this is now the second report I've made for an issue already fixed in the dev branch, I should perhaps use this dev branch of SPARK, or at least test examples against it before making reports.

Is this development version of SPARK by any chance conveniently regularly packaged as a prebuilt binary in, say, Alire, so that end users could, for example, execute a command like "alr with gnatprove-dev" to quickly set it up for testing? Or is building from source at present the only way?

**Comment by kanigsson** [comment]
The Alire version is planned to be updated only once a year. We don't mind the occasional bug report that's already fixed, so you don't need to update if it's just for the reports.
Unfortunately it's not easy to build SPARK from source, so I wouldn't recommend it. If you want to go there, let me know and I can give some directions.
