### ISSUE TITLE
Minor: `gnatprove --version` fails to show the version of Alt-Ergo.

### ISSUE THREAD

**Issue by dvraaij** [AdaCore/spark2014#43]
It seems that Alt-Ergo would like to see only 1 dash in its version argument (at least for Alt-Ergo version 2.3.3):

```shell
$ alt-ergo --version
alt-ergo: unknown option '--version'.
usage: alt-ergo [options] file.<why|mlw>
[...]
  -version                               prints the version number
[...]
```
```shell
$ alt-ergo -version
2.3.3
```

Possible solution:
```patch
--- a/src/gnatprove/configuration.adb
+++ b/src/gnatprove/configuration.adb
@@ -1260,7 +1260,7 @@ procedure Produce_Version_Output is
       if Alt_Ergo /= null then
          Ada.Text_IO.Put (Alt_Ergo.all & ": ");
          Call_With_Status (Alt_Ergo.all,
-                           Arguments => Dash_Dash_Version,
+                           Arguments => Dash_Version,
                            Status    => Status);
          Free (Alt_Ergo);
       end if;
```

**Comment by dvraaij** [comment]
According to the [changelog](https://ocamlpro.github.io/alt-ergo/About/changes.html#version-2-4-0-january-22-2021), the behavior changed as of Alt-Ergo 2.4.0. Issue can be closed.

**Comment by kanigsson** [comment]
Thanks for your report, and you are right that Alt-ergo changed the version switch a while ago.

By the way, I checked your github profile and found you are packaging SPARK for Fedora, is that right? Do you need any help?

**Comment by dvraaij** [comment]
Thanks for the offer. 

A small disclaimer: I'm not an official Fedora packager - at least not yet - though I'm trying to help the current maintainer of the Ada-related packages in Fedora to update all of them to their latest version.

I have to admit that the current package specification for SPARK is, at this point, mostly a feasibility study in which I'd like to verify if all dependencies are available and compatible. Continued availability and compatibility of dependencies can be challenging when packaging software.

I think it would be great to have SPARK available as an official package in Fedora, but before it can, I must first see if I can help updating GNATcoll (currently at v21.0.0 in Fedora) and see if I can add libgpr2 to the official repository (with the "next" extensions). Each of which may take some time.

**Comment by kanigsson** [comment]
Thanks for the info, good luck, and don't hesitate to ask questions.
