### ISSUE TITLE
Support for linux/arm64 in Host_Operating_System_Flavor

### ISSUE THREAD

**Issue by dalybrown** [AdaCore/spark2014#45]
The following enumeration supports many architectures:

https://github.com/AdaCore/spark2014/blob/50c3e8b5ae8741da6b15c8551f32d5356c2c0bac/src/common/platform.ads#L31

However, it doesn't support linux/arm64, the architecture I use (I develop in a debian docker container on my Mac M1). When building gnatprove for my architecture, I just copy/paste the amd64 version of the code since I'm not using codepeer. I seem to be able to build / use gnatprove fine afterwards. It would be nice to support this architecture too so that I don't have to workaround this when building gnatprove.

Related, I noticed another issue: when building in a linux container on an amd64 macbook, the directory is detected as `x86_64-linux-gnu`. This creates an error too. To workaround, I also copy and paste the `x86_64-linux` directory and change the name. (Also related, when building in a container on my Mac M1, it is detected as `aarch64-linux-gnu`.)

**Comment by yannickmoy** [comment]
Hi @dalybrown. We have added `Aarch64_Linux` in the enumeration, with the corresponding changes to support that build architecture. Let us know if that works for you!

Regarding the wrong identification of the host on an amd64 macbook, this is something to report to `gprbuild` project really. Finally, the architecture can go by various names, and `gprbuild` maintains a list of aliases for them.
